apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data:
  {{- if eq .Values.env "production"}}
  paymentToken: "true"
  {{ else }}
  paymentToken: "false"
  {{- end }}
  users:
    {{- range .Values.users }}
    name: {{ .name }}
    {{- end }}